#     ____             ______
#    / __ \____  ___  / ____/___  ________
#   / / / / __ \/ _ \/ /   / __ \/ ___/ _ \
#   / /_/ / / / /  __/ /___/ /_/ / /  /  __/
#   \____/_/ /_/\___/\____/\____/_/   \___/
#             by twiqk#6109 aka QuiverlyRivalry
#
#  - Config is case sensitive!
#  - Use § for colors!
#  - Open an issue for a suggestion!


# When player spawns, send them to spawn ALWAYS? [yes or no]
truespawn: "yes"


# When player joins, what should they see?
welcomemsg: "§7OneCore, a core for all. \n §7Made by twiqk."
# Should the server broadcast if a player joins? [yes or no]
customjoinmsg: "yes"
# Use {player} for player.
joinmsg: "§7{player} has joined the server! Welcome him!"
# Should the server broadcast if a player quits? [yes or no]
customquitmsg: "yes"
# Use {player} for player.
quitmsg: "§7{player} has quit the server!"


# Should the server broadcast if someone dies in PvP? [yes or no]
customdeath: "yes"
# What should the server broadcast? Use {victim} and {killer}.
deathmsg: "§c{victim} §7fell to the hands of §a{killer}"


# When admin runs /kickall what should the message be?
kickallmsg: "The server administrator \n decided to kick all players."


# Simple Broadcasting v1 [yes or no]
enablebroadcasting: "yes"
# Delay between each message in ticks? Note: 1 sec = 20 ticks
delay: 120
# Messages to be displayed, note the messages wont be displayed in any specific order!
message1: "OneCore, a core for one and all."
message2: "CastleRaid, the first Kingdoms server."
message3: "Want more features? Open an issue."
message4: "Change me in config!"

# Simple MOTD Shuffle v1 [yes or no]
enablemotdshuffle: "yes"
# Delay between each MOTD in ticks? Note: 1 sec = 20 ticks
mdelay: 120
# Messages to be displayed, note the messages wont be displayed in any specific order!
mmessage1: "OneCore, a core for one and all."
mmessage2: "CastleRaid, the first Kingdoms server."
mmessage3: "OneCore x CastleRaid"
